# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'youtube.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(460, 370)
        MainWindow.setAccessibleName("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bt_mp4 = QtWidgets.QPushButton(self.centralwidget)
        self.bt_mp4.setGeometry(QtCore.QRect(150, 180, 111, 51))
        self.bt_mp4.setObjectName("bt_mp4")
        self.bt_mp3 = QtWidgets.QPushButton(self.centralwidget)
        self.bt_mp3.setGeometry(QtCore.QRect(20, 180, 111, 51))
        self.bt_mp3.setObjectName("bt_mp3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 140, 121, 20))
        self.label_2.setObjectName("label_2")
        self.input = QtWidgets.QLineEdit(self.centralwidget)
        self.input.setGeometry(QtCore.QRect(110, 140, 331, 25))
        self.input.setObjectName("input")
        self.titulo = QtWidgets.QLineEdit(self.centralwidget)
        self.titulo.setGeometry(QtCore.QRect(100, 20, 261, 81))
        self.titulo.setCursorPosition(17)
        self.titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo.setReadOnly(True)
        self.titulo.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.titulo.setClearButtonEnabled(False)
        self.titulo.setObjectName("titulo")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(20, 240, 421, 111))
        self.listView.setObjectName("listView")
        self.download_andamento = QtWidgets.QLabel(self.centralwidget)
        self.download_andamento.setGeometry(QtCore.QRect(30, 250, 401, 31))
        self.download_andamento.setText("")
        self.download_andamento.setObjectName("download_andamento")
        self.resultado = QtWidgets.QLabel(self.centralwidget)
        self.resultado.setGeometry(QtCore.QRect(30, 310, 401, 31))
        self.resultado.setText("")
        self.resultado.setAlignment(QtCore.Qt.AlignCenter)
        self.resultado.setObjectName("resultado")
        self.tempo = QtWidgets.QProgressBar(self.centralwidget)
        self.tempo.setGeometry(QtCore.QRect(280, 190, 161, 23))
        self.tempo.setProperty("value", 0)
        self.tempo.setObjectName("tempo")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", " "))
        self.bt_mp4.setText(_translate("MainWindow", "MP4"))
        self.bt_mp3.setText(_translate("MainWindow", "MP3"))
        self.label_2.setText(_translate("MainWindow", "Insira o Link:"))
        self.titulo.setText(_translate("MainWindow", "Youtube Download "))
